# docker compose -f docker-compose.dev.yml up --build -d
# OU
# docker compose -f docker-compose.dev.yml build --no-cache
# docker compose -f docker-compose.dev.yml up -d
# API → http://localhost:8000/docs
# Frontend → http://localhost:8501

# Pour débuguer: docker compose -f docker-compose.dev.yml build --no-cache --progress=plain

# Commande POWERSHELL pour lister les utilisateurs :
# docker exec -it django_backend python manage.py shell -c "from django.contrib.auth import get_user_model; print([u.username for u in get_user_model().objects.all()])"

# Avec leurs droits :
# docker exec -it django_backend python manage.py shell -c "from django.contrib.auth import get_user_model; print([(u.username, u.is_superuser, u.is_staff) for u in get_user_model().objects.all()])"

services:
  backend:
    build: ./backend
    container_name: fastapi_backend
    ports:
      - "${FASTAPI_PORT:-8000}:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    networks:
      - appnet
    environment:
      - SMTP_HOST=${SMTP_HOST:-maildev}
      - SMTP_PORT=${SMTP_PORT:-1025}

  django:
    build: ./backend/django
    container_name: django_backend
    ports:
      - "${DJANGO_PORT:-8001}:8001"
    env_file:
      - ./backend/django/.env
    volumes:
      - ./backend/django:/app
    networks:
      - appnet

  frontend:
    build: ./frontend
    container_name: react_frontend
    ports:
      - "5173:5173"
    env_file:
      - .env
    environment:
      - VITE_BACKEND_URL=http://backend:8000
      - VITE_DJANGO_URL=http://django:8001
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
      - django
  maildev:
    image: maildev/maildev
    container_name: maildev
    ports:
      - "1080:1080" # Web UI
      - "1025:1025" # SMTP
    networks:
      - appnet

networks:
  appnet:

# Relance du cntnr front :
# docker compose -f docker-compose.dev.yml build frontend --no-cache
# docker compose -f docker-compose.dev.yml up -d frontend
