# docker compose -f docker-compose.prod.yml up --build -d
# API → http://localhost:8000/docs
# Frontend → http://localhost:80

services:
  backend:
    image: ${BACKEND_IMAGE:-ghcr.io/grcote7/pyproject_template-backend:latest}
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: fastapi_backend
    expose:
      - "8000"
    env_file:
      - ./backend/.env
    restart: always
    networks:
      - appnet
      - proxy

  django:
    image: ${DJANGO_IMAGE:-ghcr.io/grcote7/pyproject_template-django:latest}
    build:
      context: ./backend/django
      dockerfile: Dockerfile.prod
    container_name: django_backend
    expose:
      - "8001"
    env_file:
      - ./backend/django/.env
    restart: always
    networks:
      - appnet
      - proxy

  frontend:
    image: ${FRONTEND_IMAGE:-ghcr.io/grcote7/pyproject_template-frontend:latest}
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: react_frontend
    expose:
      - "80"
    env_file:
      - .env
    environment:
      - VITE_BACKEND_URL=${VITE_BACKEND_URL:-http://localhost:8000}
      - VITE_DJANGO_URL=${VITE_DJANGO_URL:-http://localhost:8001}
    depends_on:
      - backend
      - django
    restart: always
    networks:
      - appnet
      - proxy

networks:
  appnet:
  proxy:
    external: true
    name: proxy
